### ISSUE TITLE
how to train yolov7-mask model

### ISSUE THREAD

**Issue by SiChuanJay** [RizwanMunawar/yolov7-segmentation#1]
hello, I want to train a yolov7-mask model with my data, so can you show me the training steps?

**Comment by RizwanMunawar** [comment]
@SiChuanJay!
Training module will added today! It's already tested, Due to dashboard development I was not able to add that module.

**Comment by SiChuanJay** [comment]
@RizwanMunawar 
ok, it is great if the module can add today. I have some additional questions to ask you, because I need to do a real-time instance segmentation task. I have tried yolact++ and solov2, but the results are not good. Do you have any models you can recommend? Thank you very much!

**Comment by RizwanMunawar** [comment]
@SiChuanJay!
@SiChuanJay!
Sure I will add module soon. I think you can use detectron2 and unet. After that, compare result of all algorithms and decide on accuracy, f1 score etc, that which algorithm is best for your specific use-case.

**Comment by SiChuanJay** [comment]
@RizwanMunawar 
Does the Unet model support instance segmentation? Detectron2 seems to have only maskrcnn and Solov2, I didn't find any other models. Yolov7-mask looks good, hope to get good results. Thank you very much for your help

**Comment by RizwanMunawar** [comment]
@SiChuanJay!
Yes yolov7 mask is good according to my knowledge and testing. YOLOv7 is also using detectron2.

**Comment by SiChuanJay** [comment]
@RizwanMunawar 
Yes, It looks good, and hopefully it looks good on my data set.

**Comment by RizwanMunawar** [comment]
@SiChuanJay!
Training module has been added now, You can use it for your work. Thanks

**Comment by SiChuanJay** [comment]
@RizwanMunawar 
Thank you very much! But I have a question, what should that label look like? Since I used COCO datasets before, I'm not sure what this label looks like. Is it convenient for you to add a few data sets?

**Comment by RizwanMunawar** [comment]
@SiChuanJay!
Sure, will add soon after some testing.

**Comment by RizwanMunawar** [comment]
I have fix the issues in custom training. Also added the steps for Data labeling for Segmentation Task. You can check it from mentioned link below.
https://github.com/RizwanMunawar/yolov7-segmentation#custom-data-labelling
I am going to close this issue now, If you will face any issue, you can open a new issue.
