### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.uint16. 

### ISSUE THREAD

**Issue by magedhelmy1** [RizwanMunawar/yolov7-segmentation#15]
I was training the algorithm, and got this error

```
    Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
    125/299      14.5G    0.03991    0.03042     0.0524          0        857        640: 100%|██████████| 10/10 [00:03<00:00,  2.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|████████
                   all         20        356      0.611      0.604      0.545      0.239       0.58      0.598      0.524      0.204

      Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
    126/299      14.5G    0.04134    0.03091     0.0547          0        596        640:  80%|████████  | 8/10 [00:03<00:00,  2.57it/s]
Traceback (most recent call last):
  File "C:\Users\mag\projects\yolov7Mask\segment\train.py", line 681, in <module>
    main(opt)
  File "C:\Users\mag\projects\yolov7Mask\segment\train.py", line 577, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\mag\projects\yolov7Mask\segment\train.py", line 295, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\mag\projects\yolov7Mask\utils\dataloaders.py", line 171, in __iter__
    yield next(self.iterator)
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\torch\utils\data\dataloader.py", line 1356, in _next_data
    return self._process_data(data)
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\mag\projects\yolov7Mask\.env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\mag\projects\yolov7Mask\utils\segment\dataloaders.py", line 167, in __getitem__
    masks = (torch.from_numpy(masks) if len(masks) else torch.zeros(1 if self.overlap else nl, img.shape[0] //
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

I trained it using the following:

`python segment/train.py --data data-4/data.yaml --weights yolov7-seg.pt --hyp hyp.scratch-high.yaml --cfg yolov7-seg.yaml
`

Have you faced something similar?

**Comment by magedhelmy1** [comment]
This error happened because I provided the wrong "weights" file in the "--weights" argument of the code.
I provided the yolov7 instead of the yolov7-seg

**Comment by ziyeibin** [comment]
Hello, I had the same problem, but my "weights" is yolov7-seg
Here is my error：
(yolov7-seg) PS N:\develop\pyProject\yolov7-segmentation> python .\segment\train.py
segment\train: weights=yolov7-seg.pt, cfg=models\segment\yolov7-seg.yaml, data=data\coco.yaml, hyp=data\hyps\hyp.scratch-high.yaml, epochs=300, batch_size=4, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=0, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train-seg, name=exp, exist_ok=False, 
quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, mask_ratio=4, no_overlap=False
YOLOv5  yolov7-segmentation-23-g5bfd902 Python-3.10.8 torch-1.11.0+cu115 CUDA:0 (NVIDIA GeForce RTX 2070 SUPER, 8192MiB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.1, copy_paste=0.1
TensorBoard: Start with 'tensorboard --logdir runs\train-seg', view at http://localhost:6006/

                 from  n    params  module                                  arguments
  0                -1  1       928  models.common.Conv                      [3, 32, 3, 1]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  1      8320  models.common.Conv                      [128, 64, 1, 1]
  5                -2  1      8320  models.common.Conv                      [128, 64, 1, 1]
  6                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  7                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  8                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  9                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 10  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 11                -1  1     66048  models.common.Conv                      [256, 256, 1, 1]
 12                -1  1         0  models.common.MP                        []
 13                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 14                -3  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 16          [-1, -3]  1         0  models.common.Concat                    [1]
 17                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 18                -2  1     33024  models.common.Conv                      [256, 128, 1, 1]
 19                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 20                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 21                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 22                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 23  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 24                -1  1    263168  models.common.Conv                      [512, 512, 1, 1]
 25                -1  1         0  models.common.MP                        []
 26                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 27                -3  1    131584  models.common.Conv                      [512, 256, 1, 1]
 28                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 29          [-1, -3]  1         0  models.common.Concat                    [1]
 30                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 31                -2  1    131584  models.common.Conv                      [512, 256, 1, 1]
 32                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 33                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 34                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 35                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 36  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 37                -1  1   1050624  models.common.Conv                      [1024, 1024, 1, 1]
 38                -1  1         0  models.common.MP                        []
 39                -1  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 40                -3  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 41                -1  1   2360320  models.common.Conv                      [512, 512, 3, 2]
 42          [-1, -3]  1         0  models.common.Concat                    [1]
 43                -1  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 44                -2  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 45                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 46                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 47                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 48                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 49  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 50                -1  1   1050624  models.common.Conv                      [1024, 1024, 1, 1]
 51                -1  1   7609344  models.common.SPPCSPC                   [1024, 512, 1]
 52                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 53                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 54                37  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 55          [-1, -2]  1         0  models.common.Concat                    [1]
 56                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 57                -2  1    131584  models.common.Conv                      [512, 256, 1, 1]
 58                -1  1    295168  models.common.Conv                      [256, 128, 3, 1]
 59                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 60                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 61                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 62[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
 63                -1  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 64                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 65                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 66                24  1     65792  models.common.Conv                      [512, 128, 1, 1]
 67          [-1, -2]  1         0  models.common.Concat                    [1]
 68                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 69                -2  1     33024  models.common.Conv                      [256, 128, 1, 1]
 70                -1  1     73856  models.common.Conv                      [128, 64, 3, 1]
 71                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 72                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 73                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 74[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
 75                -1  1     65792  models.common.Conv                      [512, 128, 1, 1]
 76                -1  1         0  models.common.MP                        []
 77                -1  1     16640  models.common.Conv                      [128, 128, 1, 1]
 78                -3  1     16640  models.common.Conv                      [128, 128, 1, 1]
 79                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 80      [-1, -3, 63]  1         0  models.common.Concat                    [1]
 81                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 82                -2  1    131584  models.common.Conv                      [512, 256, 1, 1]
 83                -1  1    295168  models.common.Conv                      [256, 128, 3, 1]
 84                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 85                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 86                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 87[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
 88                -1  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 89                -1  1         0  models.common.MP                        []
 90                -1  1     66048  models.common.Conv                      [256, 256, 1, 1]
 91                -3  1     66048  models.common.Conv                      [256, 256, 1, 1]
 92                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 93      [-1, -3, 51]  1         0  models.common.Concat                    [1]
 94                -1  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 95                -2  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 96                -1  1   1180160  models.common.Conv                      [512, 256, 3, 1]
 97                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 98                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 99                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
100[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
101                -1  1   1049600  models.common.Conv                      [2048, 512, 1, 1]
102                75  1    295424  models.common.Conv                      [128, 256, 3, 1]
103                88  1   1180672  models.common.Conv                      [256, 512, 3, 1]
104               101  1   4720640  models.common.Conv                      [512, 1024, 3, 1]
105   [102, 103, 104]  1   1411586  models.yolo.ISegment                    [4, [[12, 16, 19, 36, 40, 28], [36, 75, 76, 55, 72, 146], [142, 110, 192, 243, 459, 401]], 32, 256, [256, 512, 1024]]
yolov7-seg summary: 417 layers, 37882274 parameters, 37882274 gradients, 142.7 GFLOPs

Transferred 555/565 items from yolov7-seg.pt
AMP: checks passed 
optimizer: SGD(lr=0.01) with parameter groups 98 weight(decay=0.0), 95 weight(decay=0.0005), 95 bias
train: Scanning 'N:\develop\pyProject\yolov7-segmentation\coco\labels\train.cache' images and labels... 19 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 19/19 [00:00<?, ?it/s]
val: Scanning 'N:\develop\pyProject\yolov7-segmentation\coco\labels\val.cache' images and labels... 7 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 7/7 [00:00<?, ?it/s]

AutoAnchor: 4.58 anchors/target, 0.998 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Plotting labels to runs\train-seg\exp4\labels.jpg... 
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs\train-seg\exp4
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
      0/299      5.87G     0.1198      0.155     0.2091    0.02682        346        640:  80%|████████  | 4/5 [00:02<00:00,  1.69it/s]
Traceback (most recent call last):
  File "N:\develop\pyProject\yolov7-segmentation\segment\train.py", line 681, in <module>
    main(opt)
  File "N:\develop\pyProject\yolov7-segmentation\segment\train.py", line 577, in main
    train(opt.hyp, opt, device, callbacks)
  File "N:\develop\pyProject\yolov7-segmentation\segment\train.py", line 295, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "N:\develop\pyProject\yolov7-segmentation\utils\dataloaders.py", line 171, in __iter__
    yield next(self.iterator)
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "N:\develop\pyProject\yolov7-segmentation\utils\segment\dataloaders.py", line 167, in __getitem__
    masks = (torch.from_numpy(masks) if len(masks) else torch.zeros(1 if self.overlap else nl, img.shape[0] //
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by RizwanMunawar** [comment]
@ziyeibin! Seems like the training process was started, but in 4th epoch, it threw an error. Maybe some files have been corrupted! I think with retraining this issue can be resolved.
