### ISSUE TITLE
can some custom dataset supply?for excmple car dataset

### ISSUE THREAD

**Issue by futureflsl** [RizwanMunawar/yolov7-segmentation#16]
I saw article https://chr043416.medium.com/train-yolov7-segmentation-on-custom-data-b91237bd2a29,but I cannot understand the trainning labels image.the mask like labelme_json_to_dataset converted image or image  pixel is class index?can some car dataset supply?

**Comment by RizwanMunawar** [comment]
@futureflsl! Yes, you can create a dataset from different videos available on the internet that contains cars, and then label data in segmentation format, After that, you can train the segmentation model by following the link you shared.
https://chr043416.medium.com/train-yolov7-segmentation-on-custom-data-b91237bd2a29

Article Link: (How to develop Dataset from online videos)
https://medium.com/nerd-for-tech/extraction-of-frames-from-a-single-video-2b9fdd901208

**Comment by RizwanMunawar** [comment]
Since a long time, there is no update on this. I am closing this issue for now. Feel free to open new issue, if you will face any issue.
