### ISSUE TITLE
my custom dataset is does not works.

### ISSUE THREAD

**Issue by Syc056** [RizwanMunawar/yolov7-segmentation#18]
I make custom dataset with black box driving video on the road.
and it find road crack and pothole.
but it is does not work. 
can you help me? 
i have no idea except you.
thanks.

**Comment by RizwanMunawar** [comment]
@Syc056! Did you label data correctly? For how many epochs you have trained the segmentation model?

**Comment by Syc056** [comment]
before my label type is coco dataset format but i convert this to yolo.
like under
class number  x coord * image's width  y coord * image's height x coord * image's width  y coord * image's height  . . . . . .
class number  x coord * image's width  y coord * image's height x coord * image's width  y coord * image's height  . . . . . .
. 
. 
.
like this .
can you imagnine what can be problem? help me if you have any other Q tell me i wnana solve this problem quicklily 
thanks

**Comment by RizwanMunawar** [comment]
@Syc056! Please try to follow the exact steps that are mentioned in the article shared below. I have tested training on custom data, by labeling the data on Roboflow. Other conversions etc, might create an issues!

https://medium.com/augmented-startups/train-yolov7-segmentation-on-custom-data-b91237bd2a29
