### ISSUE TITLE
Is it possible to use pretrained weights from yolov7 object detection & classification model?

### ISSUE THREAD

**Issue by hannaliavoshka** [RizwanMunawar/yolov7-segmentation#19]
I have trained a classic yolov7 model with object detection and classification task. Can I use these weights as a starting point to train the yolov7-segmentation model on another dataset?

**Comment by RizwanMunawar** [comment]
@hannaliavoshka! No, segmentation model is different from (detection + classification) model. 
According to my understanding, you can done your work by following the mention steps.
a) [Train YOLOv7 segmentation model on your custom data](https://medium.com/augmented-startups/train-yolov7-segmentation-on-custom-data-b91237bd2a29), you will get detection and segmentation in output.
b) Train classifier on custom data.
c) Integrate classifier with (detection + segmentation) code.

**Comment by hannaliavoshka** [comment]
Thank you very much, nice work!
