### ISSUE TITLE
KeyError: 'loss_ota'

### ISSUE THREAD

**Issue by yuzhj** [RizwanMunawar/yolov7-segmentation#2]
I get an error when I use your code
![image](https://user-images.githubusercontent.com/31239926/186375060-f54f5e70-2aa4-473c-8815-ace2205c523b.png)
Haven't you met this problem before?

**Comment by RizwanMunawar** [comment]
It seems like your gpu module is not working fine.
Can you share the command, you have used for training?
Also can try to run training without gpu?

**Comment by yuzhj** [comment]
There is the command I used
`python train.py --weights=yolov7-mask.pt --cfg .\cfg\yolov7-mask.yaml --batch-size 4 --img 256 --hyp .\data\hyp.scratch.mask.yaml --data .\data\coco.yaml --workers 0`
I will try to run training without gpu later

**Comment by yuzhj** [comment]
I find the file hyp.scratch.mask.yaml doesn't have the key 'loss_ota', but when I add the key into hyp.scratch.mask.yaml, I meet another error.

**Comment by RizwanMunawar** [comment]
Thanks, Can you share the new error you have faced? "loss_ota" is used to fast the training process, but I don't think it will effect any training results?.

**Comment by yuzhj** [comment]
> Thanks, Can you share the new error you have faced? "loss_ota" is used to increase or decrease speed of the training process, but I don't think it will effect any training results?.
Here is the new error I met
![image](https://user-images.githubusercontent.com/31239926/186398872-e86b8b45-9fff-484f-be4c-4902df081ef9.png)

**Comment by RizwanMunawar** [comment]
@yuzhj! give me sometime to fix this issue, Meanwhile if You will sort this issue, you can send pull request. Thanks

**Comment by yuzhj** [comment]
> 

Thanks in advance

**Comment by RizwanMunawar** [comment]
I have fix the issues in custom training. Also added the steps for **Data labeling for Segmentation Task**. You can check it from mentioned link below.
https://github.com/RizwanMunawar/yolov7-segmentation#custom-data-labelling
I am going to close this issue now, If you will face any issue, you can open a new issue.
