### ISSUE TITLE
Training on unlabelled images

### ISSUE THREAD

**Issue by kzchua1998** [RizwanMunawar/yolov7-segmentation#24]
Hi Rizwan, first of all thank you so much for your source codes, they are very useful. However, may I know is it possible to have the instance segmentation model trained on unlabelled images? (intended to reduce false positives) If so, how should it be done? I have tried training with (empty) and without annotation .txt file and none of them work. Thank you in advance.

**Comment by RizwanMunawar** [comment]
@kzchua199! Well, you can not do instance segmentation with unlabeled images. The way that you can follow, if you don't want to label the data manually is mentioned below.

_Use the default pretrain model for data labeling. i.e. if you want to train the model for people segmentation only, so first segment the person in your dataset by running mentioned command below._
```
python segment/predict.py --weights yolov7-seg.pt --source "your image folder path" --classes 0 --save-txt
```
_It will generate the label files for your images. Then, you can use these label files to train your custom model._ 

But I will always recommend to label dataset manually.

**Comment by RizwanMunawar** [comment]
@kzchua1998! I am closing this issue, as there is no update since last few days. Feel free to open new issue, if you will face any problem.
