### ISSUE TITLE
training labels format 

### ISSUE THREAD

**Issue by ghost** [RizwanMunawar/yolov7-segmentation#3]
what annotation format should we use ? i tried json2yolo but i am facing many errors , i also tried yolo text format polygon but no labels detected

**Comment by RizwanMunawar** [comment]
@farooq3211! I am working on this task. Soon I will add complete steps to train instance segmentation on custom data in efficient way.

**Comment by RizwanMunawar** [comment]
I have fix the issue you have faced in custom training. Also added the steps for **Data labeling for Segmentation Task**. You can check it from mentioned link below.
https://github.com/RizwanMunawar/yolov7-segmentation#custom-data-labelling
