### ISSUE TITLE
which tools can show the labels files of segmentation?

### ISSUE THREAD

**Issue by stphtan94117** [RizwanMunawar/yolov7-segmentation#30]
i enable --save-txt module and get label  txt of segmentation.
So, do you know which tool can show those txt?

labelme can not open txt. it only support json.
labelimg only support rectangle txt, not polygon txt.

another question
can you add function to calculate the area for segmentation?
for example, i detect crack on wall, and I would want to know the crack size.
thanks a lot

**Comment by RizwanMunawar** [comment]
@stphtan94117! You can use Roboflow online app to verify the segmentation labels. 
Thanks for the suggestions, I will work on that, and asap, area of segmentation will be a part of code.

**Comment by stphtan94117** [comment]
@RizwanMunawar 
HI,Sir
Is it possible to make a python file for converting txt (yolo) to json(labelme) and json to yolo?

i know Roboflow online can convert and read files
but my datasets are huge, I would not spend a lot of time to upload or adjust it.

i just want to use labelme to edit and check the segmentation labels. It is convenient for me
Can you make a python to covert txt2yolo and yolo2txt?
very thanks

**Comment by RizwanMunawar** [comment]
@stphtan94117! I am working on this, but due to other modules development this can be delayed. I am closing this issue for now, as its enhancement in the latest code. Feel free to open a new issue, if you will face any error in latest code.
