### ISSUE TITLE
TensorRT export trials

### ISSUE THREAD

**Issue by jordandroid** [RizwanMunawar/yolov7-segmentation#31]
Hello,

I would like to export my custom trained model with this YoloV7-segmentation to TensorRT.
I tried to use basic script to export classic yolov7  to TensorRT (torch to ONNX then ONNX to TRT), it works but seems to loose segmentation part.
I get 5 outputs, including one of size 819200 but I do not know if this output can be used to get segmentation or if all the parts  related to segmentation are lost during export.

Respectfully,
Jordan

**Comment by RizwanMunawar** [comment]
@jordandroid! Currently export module is not a part of code, I am working on that. In next release, it will be a part of master branch.

**Comment by jordandroid** [comment]
Thanks for your work, I saw that is was not part of code but wanted to try on my self to look at it and found missing parts.
Nice to hear that it will be part of next release, congratulation for your work

**Comment by RizwanMunawar** [comment]
@jordandroid! That great, feel free to open a pull request if you think that you have proper way to convert pytorch to tensorrt model.
I am closing this issue for now, feel free to open a new one if you will face any issue.
