### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.uint16. 

### ISSUE THREAD

**Issue by ziyeibin** [RizwanMunawar/yolov7-segmentation#32]
I checked issuse and found that there was the same problem. but my "weights" is yolov7-seg。 I don't know how to handle the error. Here is my error report. Can you help me
(yolov7-seg) PS N:\develop\pyProject\yolov7-segmentation> python .\segment\train.py
segment\train: weights=yolov7-seg.pt, cfg=models\segment\yolov7-seg.yaml, data=data\coco.yaml, hyp=data\hyps\hyp.scratch-high.yaml, epochs=300, batch_size=4, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=0, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs\train-seg, name=exp, exist_ok=False, 
quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, mask_ratio=4, no_overlap=False
YOLOv5  yolov7-segmentation-23-g5bfd902 Python-3.10.8 torch-1.11.0+cu115 CUDA:0 (NVIDIA GeForce RTX 2070 SUPER, 8192MiB)

hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.1, copy_paste=0.1
TensorBoard: Start with 'tensorboard --logdir runs\train-seg', view at http://localhost:6006/

                 from  n    params  module                                  arguments
  0                -1  1       928  models.common.Conv                      [3, 32, 3, 1]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  1      8320  models.common.Conv                      [128, 64, 1, 1]
  5                -2  1      8320  models.common.Conv                      [128, 64, 1, 1]
  6                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  7                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  8                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
  9                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 10  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 11                -1  1     66048  models.common.Conv                      [256, 256, 1, 1]
 12                -1  1         0  models.common.MP                        []
 13                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 14                -3  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 16          [-1, -3]  1         0  models.common.Concat                    [1]
 17                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 18                -2  1     33024  models.common.Conv                      [256, 128, 1, 1]
 19                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 20                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 21                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 22                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 23  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 24                -1  1    263168  models.common.Conv                      [512, 512, 1, 1]
 25                -1  1         0  models.common.MP                        []
 26                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 27                -3  1    131584  models.common.Conv                      [512, 256, 1, 1]
 28                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 29          [-1, -3]  1         0  models.common.Concat                    [1]
 30                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 31                -2  1    131584  models.common.Conv                      [512, 256, 1, 1]
 32                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 33                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 34                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 35                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 36  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 37                -1  1   1050624  models.common.Conv                      [1024, 1024, 1, 1]
 38                -1  1         0  models.common.MP                        []
 39                -1  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 40                -3  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 41                -1  1   2360320  models.common.Conv                      [512, 512, 3, 2]
 42          [-1, -3]  1         0  models.common.Concat                    [1]
 43                -1  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 44                -2  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 45                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 46                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 47                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 48                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 49  [-1, -3, -5, -6]  1         0  models.common.Concat                    [1]
 50                -1  1   1050624  models.common.Conv                      [1024, 1024, 1, 1]
 51                -1  1   7609344  models.common.SPPCSPC                   [1024, 512, 1]
 52                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 53                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 54                37  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 55          [-1, -2]  1         0  models.common.Concat                    [1]
 56                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 57                -2  1    131584  models.common.Conv                      [512, 256, 1, 1]
 58                -1  1    295168  models.common.Conv                      [256, 128, 3, 1]
 59                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 60                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 61                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 62[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
 63                -1  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 64                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 65                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 66                24  1     65792  models.common.Conv                      [512, 128, 1, 1]
 67          [-1, -2]  1         0  models.common.Concat                    [1]
 68                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 69                -2  1     33024  models.common.Conv                      [256, 128, 1, 1]
 70                -1  1     73856  models.common.Conv                      [128, 64, 3, 1]
 71                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 72                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 73                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]
 74[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
 75                -1  1     65792  models.common.Conv                      [512, 128, 1, 1]
 76                -1  1         0  models.common.MP                        []
 77                -1  1     16640  models.common.Conv                      [128, 128, 1, 1]
 78                -3  1     16640  models.common.Conv                      [128, 128, 1, 1]
 79                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 80      [-1, -3, 63]  1         0  models.common.Concat                    [1]
 81                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 82                -2  1    131584  models.common.Conv                      [512, 256, 1, 1]
 83                -1  1    295168  models.common.Conv                      [256, 128, 3, 1]
 84                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 85                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 86                -1  1    147712  models.common.Conv                      [128, 128, 3, 1]
 87[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
 88                -1  1    262656  models.common.Conv                      [1024, 256, 1, 1]
 89                -1  1         0  models.common.MP                        []
 90                -1  1     66048  models.common.Conv                      [256, 256, 1, 1]
 91                -3  1     66048  models.common.Conv                      [256, 256, 1, 1]
 92                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 93      [-1, -3, 51]  1         0  models.common.Concat                    [1]
 94                -1  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 95                -2  1    525312  models.common.Conv                      [1024, 512, 1, 1]
 96                -1  1   1180160  models.common.Conv                      [512, 256, 3, 1]
 97                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 98                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
 99                -1  1    590336  models.common.Conv                      [256, 256, 3, 1]
100[-1, -2, -3, -4, -5, -6]  1         0  models.common.Concat                    [1]
101                -1  1   1049600  models.common.Conv                      [2048, 512, 1, 1]
102                75  1    295424  models.common.Conv                      [128, 256, 3, 1]
103                88  1   1180672  models.common.Conv                      [256, 512, 3, 1]
104               101  1   4720640  models.common.Conv                      [512, 1024, 3, 1]
105   [102, 103, 104]  1   1411586  models.yolo.ISegment                    [4, [[12, 16, 19, 36, 40, 28], [36, 75, 76, 55, 72, 146], [142, 110, 192, 243, 459, 401]], 32, 256, [256, 512, 1024]]
yolov7-seg summary: 417 layers, 37882274 parameters, 37882274 gradients, 142.7 GFLOPs

Transferred 555/565 items from yolov7-seg.pt
AMP: checks passed 
optimizer: SGD(lr=0.01) with parameter groups 98 weight(decay=0.0), 95 weight(decay=0.0005), 95 bias
train: Scanning 'N:\develop\pyProject\yolov7-segmentation\coco\labels\train.cache' images and labels... 19 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 19/19 [00:00<?, ?it/s]
val: Scanning 'N:\develop\pyProject\yolov7-segmentation\coco\labels\val.cache' images and labels... 7 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 7/7 [00:00<?, ?it/s]

AutoAnchor: 4.58 anchors/target, 0.998 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Plotting labels to runs\train-seg\exp4\labels.jpg... 
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs\train-seg\exp4
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size
      0/299      5.87G     0.1198      0.155     0.2091    0.02682        346        640:  80%|████████  | 4/5 [00:02<00:00,  1.69it/s]
Traceback (most recent call last):
  File "N:\develop\pyProject\yolov7-segmentation\segment\train.py", line 681, in <module>
    main(opt)
  File "N:\develop\pyProject\yolov7-segmentation\segment\train.py", line 577, in main
    train(opt.hyp, opt, device, callbacks)
  File "N:\develop\pyProject\yolov7-segmentation\segment\train.py", line 295, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "N:\develop\pyProject\yolov7-segmentation\utils\dataloaders.py", line 171, in __iter__
    yield next(self.iterator)
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "K:\soft\anaconda\envs\yolov7-seg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "N:\develop\pyProject\yolov7-segmentation\utils\segment\dataloaders.py", line 167, in __getitem__
    masks = (torch.from_numpy(masks) if len(masks) else torch.zeros(1 if self.overlap else nl, img.shape[0] //
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by ziyeibin** [comment]
(yolov7-seg) PS N:\develop\pyProject\yolov7-segmentation> conda list
# packages in environment at K:\soft\anaconda\envs\yolov7-seg:
#
# Name                    Version                   Build  Channel
absl-py                   1.3.0                    pypi_0    pypi
asttokens                 2.1.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bzip2                     1.0.8                he774522_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2022.10.11           haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.9.24       py310haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
charset-normalizer        2.1.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
google-auth               2.14.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.50.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.22.4                   pypi_0    pypi
ipython                   8.6.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
libffi                    3.4.2                hd77b12b_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
networkx                  2.8.8                    pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.1                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2          py310haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
prompt-toolkit            3.0.32                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.10.8               hbb2ffb3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.6                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
seaborn                   0.12.1                   pypi_0    pypi
setuptools                65.5.0          py310haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.16.0                   pypi_0    pypi
sqlite                    3.39.3               h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
stack-data                0.6.1                    pypi_0    pypi
tensorboard               2.11.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
tifffile                  2022.10.10               pypi_0    pypi
tk                        8.6.12               h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch                     1.11.0+cu115             pypi_0    pypi
torchaudio                0.11.0+cu115             pypi_0    pypi
torchvision               0.12.0+cu115             pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2022f                h04d1e81_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 h21ff451_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
vs2015_runtime            14.27.29016          h5e58377_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wincertstore              0.2             py310haa95532_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.6                h8cc25b3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zlib                      1.2.13               h8cc25b3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by RizwanMunawar** [comment]
@ziyeibin! Seems like the training process was started, but after some time, it threw an error. Maybe some files have been corrupted! I think with retraining this issue can be resolved.

**Comment by ziyeibin** [comment]
retraining ?I've tried many times and the result is the same. It's the same error

**Comment by RizwanMunawar** [comment]
@ziyeibin! ok 
Please share the mentioned details below, in order to understand the issue and resolve it in proper way.
a) Did you follow the article to label the dataset?https://medium.com/augmented-startups/train-yolov7-segmentation-on-custom-data-b91237bd2a29
b) Can you share the dataset for testing?

**Comment by ziyeibin** [comment]
Thank you. I'd like to see the document

**Comment by ziyeibin** [comment]
I think it's the problem I marked with labelme. Thank you for your help

**Comment by RizwanMunawar** [comment]
@ziyeibin! That great, your issue has been resolved.

**Comment by ziyeibin** [comment]
@RizwanMunawar I need help. I failed. I can't handle this problem. My network can't be connected to roboflow, so I used labelme. And converting datasets to yolo datasets. I can't confirm the problem. I'm upset，If you have time, please help me. Thank you
labelme2yolo
https://github.com/SuperLuu7/labelme2yolo
This is my dataset link
data
https://www.aliyundrive.com/s/njDh4SNsWiy

**Comment by RizwanMunawar** [comment]
@ziyeibin! I haven't tested with LabelMe. In coming days, maybe I will add the data labeling procedure on local system for segmentation!

**Comment by ziyeibin** [comment]
I also uploaded the yolo dataset after lebalme conversion. Can you try my yolo dataset?

**Comment by ziyeibin** [comment]
The problem has been solved

**Comment by RizwanMunawar** [comment]
@ziyeibin! Fine, Can you share the workflow about **How you resolved the issue**? This will help people to learn and resolve their issues easily. Thanks

**Comment by kidserge-yong** [comment]
If anyone still have this problem after use the correct weight.
I recommend to check your GPU memory.

I do not discovery the cause but whenever model took more than 90% GPU memory, there is a chance this bug will happen.
Try to use no more than 90% of GPU memory, reduce batch size also help.

**Comment by chenyutao97** [comment]
Hello, how to solve the above problem?

**Comment by RizwanMunawar** [comment]
@chenyutao97 you can check GPU memory As @kidserge-yong said above, If GPU memory utilization is more than 90%, this can cause such an issue. 

Apart from that, make sure that you have annotated the data with Roboflow, otherwise with another labeling tool, such kind of errors can come.

**Comment by chenyutao97** [comment]
Thanks for your reply.But I don't think it's for that reason.Can you give me an email address if it is convenient? I want to send you my dataset, which is very small and only 100 sheets.

**Comment by chenyutao97** [comment]
My network can't be connected to roboflow, so I used labelme. And converting datasets to yolo datasets.

**Comment by chenyutao97** [comment]
Traceback (most recent call last):
  File "D:/yolov7-seg/yolov7-segmentation-main/segment/train.py", line 681, in <module>
    main(opt)
  File "D:/yolov7-seg/yolov7-segmentation-main/segment/train.py", line 577, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:/yolov7-seg/yolov7-segmentation-main/segment/train.py", line 295, in train
    for i, (imgs, targets, paths, _, masks) in pbar:  # batch ------------------------------------------------------
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\yolov7-seg\yolov7-segmentation-main\utils\dataloaders.py", line 171, in __iter__
    yield next(self.iterator)
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\yolov7\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\yolov7-seg\yolov7-segmentation-main\utils\segment\dataloaders.py", line 167, in __getitem__
    masks = (torch.from_numpy(masks) if len(masks) else torch.zeros(1 if self.overlap else nl, img.shape[0] //
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by kidserge-yong** [comment]
@chenyutao97 Did it start training?
The previous problem is the system starts training but after some time the error happens.
If your case is the same please shared your machine component (CPU, GPU), and training parameter (batch_size, image_size).

**Comment by chenyutao97** [comment]
Hello, the problem with my dataset occurred before the training started.For some reasons, I can only annotate the data with labelme and then convert the format.If you have time, can you help me see where the problem is？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RizwanMunawar/yolov7-segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月28日(星期天) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RizwanMunawar/yolov7-segmentation] TypeError: can't convert np.ndarray of type numpy.uint16.  (Issue #32)





 
@chenyutao97 Did it start training?
 The previous problem is the system starts training but after some time the error happens.
 If your case is the same please shared your machine component (CPU, GPU), and training parameter (batch_size, image_size).
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

33.zip (292.43M, 2023年06月27日 15:35 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=09373735cd77dbdfd4ced77c1e62501d4a4304020b0104561f060e0d5d4f030703531a075d01531f06010f0c5d525351025302033864620101194d5c48625f&code=27758bb2

**Comment by RizwanMunawar** [comment]
@chenyutao97 I have not used labelme for the annotations of segmentation data, so not sure how to resolve this issue you faced. I will suggest rechecking the conversion code of segmentation data to YOLO format after labelme annotation, seems, there is some issue in the conversion code.

**Comment by chenyutao97** [comment]
This is the JSON dataset and conversion file.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "RizwanMunawar/yolov7-segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月27日(星期六) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RizwanMunawar/yolov7-segmentation] TypeError: can't convert np.ndarray of type numpy.uint16.  (Issue #32)





 
@chenyutao97 you can check GPU memory As @kidserge-yong said above, If GPU memory utilization is more than 90%, this can cause such an issue.
 
Apart from that, make sure that you have annotated the data with Roboflow, otherwise with another labeling tool, such kind of errors can come.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

222.zip (440.34M, 2023年06月27日 15:48 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5836653565ad1c8782cf857c4730544c1c42075455555200490f5553541d0357575748055852024e020e505453560456020f00576137665156044b4f0840665e&code=d6e5a0fc

**Comment by chenyutao97** [comment]
My current speculation is that this situation may occur when there are too many labeled masks in the image.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RizwanMunawar/yolov7-segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月28日(星期天) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RizwanMunawar/yolov7-segmentation] TypeError: can't convert np.ndarray of type numpy.uint16.  (Issue #32)





 
@chenyutao97 I have not used labelme for the annotations of segmentation data, so not sure how to resolve this issue you faced. I will suggest rechecking the conversion code of segmentation data to YOLO format after labelme annotation, seems, there is some issue in the conversion code.
