### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by Sarveshsh8** [RizwanMunawar/yolov7-segmentation#38]
How to create a custom inference using model.torch.hub load for instance segmentaion

**Comment by RizwanMunawar** [comment]
@Sarveshsh8! You will need to label your custom data in Polygon format, then you will need to train the segmentation model on custom data.
For more details and workflow you can visit mentioned link below.
https://medium.com/augmented-startups/train-yolov7-segmentation-on-custom-data-b91237bd2a29
