### ISSUE TITLE
mosaic 

### ISSUE THREAD

**Issue by whiterAutumn** [RizwanMunawar/yolov7-segmentation#40]
Hello! Thank you for your repository. Now I want to ask you a question.
Because the training took a long time, I tried to set the mosaic enhancement coefficient to 0.5 in ### data/hyps/hyp.scratch-high.yaml, but report error looks like this:
 ```
 File "home/user/yolov7/seg/utils/segment/dataloaders.py", line 143, in __getitem__
    img, labels, segments = random_perspective(
TypeError: random_perspective() got an unexpected keyword argument 'return_seg'`
```

**Comment by Kunlei-Hong** [comment]
I just met the same question. Have you resolved it ?

**Comment by whiterAutumn** [comment]
sorry, i don't solved!

**Comment by abdulwaheedsoudagar** [comment]
I didn't need mosaic so after commenting line 152 in file seg/utils/segment/dataloaders.py, it worked for me.
![image](https://user-images.githubusercontent.com/20552376/228614920-8d035222-f66f-4d67-a0d9-9ee11dc04864.png)

**Comment by RizwanMunawar** [comment]
@abdulwaheedsoudagar Thanks for the Info. It will help many people to run the code smoothly.
