### ISSUE TITLE
Difference to YOLO7 u7 branch?

### ISSUE THREAD

**Issue by Robotatron** [RizwanMunawar/yolov7-segmentation#41]
The YOLO7 u7 branch also supports instance segmentation. 
How does this repo differ from it?

**Comment by RizwanMunawar** [comment]
@Robotatron! This repo has also been taken from the u7 branch. But there were a lot of issues in the u7 branch, Which I resolved and apart from that added many other features i.e object tracking with instance segmentation, save-txt option, ready-to-use colab, etc.

**Comment by RizwanMunawar** [comment]
@Robotatron! I am closing this issue for now, as it's a question not an issue in code.
I would suggest you ask your queries in the discussion section of the repository. You can check the discussion section from the mentioned link below.
https://github.com/RizwanMunawar/yolov7-segmentation/discussions
