### ISSUE TITLE
Dataset quantity.

### ISSUE THREAD

**Issue by gyupro** [RizwanMunawar/yolov7-segmentation#45]
Thanks for great work.

I was wondering how many data you have used to make this possible and how long it takes to get train done.

Thank you in advance.

**Comment by RizwanMunawar** [comment]
@gyupro! If you have more than 1k+ samples, then you easily achieve good accuracy with the modification of a few parameters. I have used 1.5k image samples for training and POCs.

**Comment by gyupro** [comment]
Thanks for your great advice.
