### ISSUE TITLE
Do you have any plan for larger model?

### ISSUE THREAD

**Issue by yellowjs0304** [RizwanMunawar/yolov7-segmentation#49]
Hi, Thank you for sharing nice work.

Do you have any plan for larger segmentation model(like yolov7x) in yolov7? 

I want more large model for accuracy.

**Comment by RizwanMunawar** [comment]
Hi @yellowjs0304! Currently, I don't have a plan for this, coz currently I am working on stuff related to YOLOv8, but next month maybe I will work on this too. Thanks.

**Comment by yellowjs0304** [comment]
Thank you, I got it.
