### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0

### ISSUE THREAD

**Issue by HassanBinAli** [RizwanMunawar/yolov7-segmentation#52]
Hey! Hope you are doing fine. When I try to run `!python segment/train.py --data data/custom.yaml --batch 4 --weights "yolov7-seg.pt" --cfg yolov7-seg.yaml --epochs 15 --name yolov7-seg --img 640 --hyp data/hyps/hyp.scratch-high.yaml`, It throws the following error
![Capture](https://user-images.githubusercontent.com/87352841/215564110-ffe019a3-2de4-4c75-a36f-375a1d76eccd.PNG)

**Comment by RizwanMunawar** [comment]
@HassanBinAli! Seems like your labels are not in the correct format. Make sure that your annotations need to be in polygon format, not in bounding box format, and not in (the wrong transformation from label me json to yolo format). Otherwise, training will not work.

**Comment by HassanBinAli** [comment]
Yes you are right. My annotations are basically bounding boxes though they are in yolov7 format. Thank you.

**Comment by Skmadigan** [comment]
@HassanBinAli and @RizwanMunawar , I am having the same issue.  Could you please explain how to change bounding box annotations into polygons?  I am new to this.  Thanks!

**Comment by RizwanMunawar** [comment]
@Skmadigan! You can not convert bounding box annotations directly into polygons! You will need to label the data in segmentation format on roboflow or some other tool!

**Comment by lev-enzo** [comment]
I have coco-style segmentations (each dataset['annotation'] has 'segmentation' key.
Here I have two questions:
1 - can you suggest how the labels should be? also one text file per each image? if so what is the shape of the file (maybe you have an example?)
2 - some of the annotations are not in polygons but in uncompressed RLE  - is it a problem? 
I did not find a way to convert the annotations, only masks (https://github.com/cocodataset/cocoapi/issues/135) but i guess it is irrelevant here?

Thanks a lot.

**Comment by RizwanMunawar** [comment]
@lev-enzo! the Segmentation labels must be in YOLO label style format. You can use roboflow for conversion of coco annotation to the right Segmentation format, which YOLOv7 required.
