### ISSUE TITLE
Is there an interpretation video for the predict.py code?

### ISSUE THREAD

**Issue by lxr1137805288** [RizwanMunawar/yolov7-segmentation#56]
Is there an interpretation video for the predict.py code?
How to read and modify it to your own Python API?

**Comment by RizwanMunawar** [comment]
@lxr1137805288 your queries in related to additional modules. It's not related to the issue in the existing code. I will recommend posting your queries related to additional modules in the [Discussion](https://github.com/RizwanMunawar/yolov7-segmentation/discussions) section. Thanks
