### ISSUE TITLE
Segmentation: Binary Mask instead of Mask Overlay

### ISSUE THREAD

**Issue by nilushacj** [RizwanMunawar/yolov7-segmentation#58]
Hello. When obtaining the instance segmentation for an image, how can I get a binary mask (white representing areas of segmented regions/pixels and black representing the rest) instead of the current output (which is a mask overlay)?

I'd really appreciate some feedback on this

**Comment by nilushacj** [comment]
I found the solution. For anyone interested, you can accomplish this by modifying the 'plot_masks' function in 'plots.py' where you can replace 'img_gpu' by an empty tensor.

**Comment by ytl0623** [comment]
How did you do that!!!
I found the code in plots.py and edit: img_gpu = torch.empty(0,1), but it didn't work.
Could you please help me?

Thanks!!!

**Comment by nilushacj** [comment]
Try "img_gpu.zero_()"

**Comment by ytl0623** [comment]
It works!!! Big Thanks!!!
