### ISSUE TITLE
segmentation color and coordinates

### ISSUE THREAD

**Issue by lordfarquad3211** [RizwanMunawar/yolov7-segmentation#6]
how to locate the coordinates of the segmented area and how to change the color of it ?

**Comment by RizwanMunawar** [comment]
@lordfarquad3211, In [segment/predict.py](https://github.com/RizwanMunawar/yolov7-segmentation/blob/main/segment/predict.py) file, see this [line-170](https://github.com/RizwanMunawar/yolov7-segmentation/blob/916ddaca7a73ec2bdb79baae7afb8e5dd54f4776/segment/predict.py#L170), it will provide you coordinates of the segmented area.
To change the color of the box, in the [utils/plot.py](https://github.com/RizwanMunawar/yolov7-segmentation/blob/main/utils/plots.py) file, see this [line-37](https://github.com/RizwanMunawar/yolov7-segmentation/blob/main/utils/plots.py#L37), it will provide you the option to change the color of class according to your need.

**Comment by lordfarquad3211** [comment]
it will give me the coordinates of the bounding box not the segmented area

**Comment by aqsc** [comment]
> it will give me the coordinates of the bounding box not the segmented area, any idea ?

Have you solved that？

**Comment by magedhelmy1** [comment]
@RizwanMunawar  @lordfarquad3211  @aqsc 

I provided the` --save-txt` argument to the `python3 segment/predict.py` and you get a file with the bounding boxes like below

```
0 0.26901 0.368056 0.0234375 0.0435185
0 0.908594 0.969907 0.0338542 0.037963
```

Have any of you managed to get the coordinates of the polygon/Segmentation area?

**Comment by magedhelmy1** [comment]
@RizwanMunawar, just to update you on this issue. If you run --save-txt on the YoloV5 segment, you actually get the mask coordinates and not the bounding box. So I guess it is perhaps a matter of updating this Repo with the YoloV5 segmentation. Thank you for all the work!

**Comment by magedhelmy1** [comment]
@RizwanMunawar  please check [#22](https://github.com/RizwanMunawar/yolov7-segmentation/pull/22)

**Comment by RizwanMunawar** [comment]
@magedhelmy1! Sure I will check and merge it in master branch.

**Comment by RizwanMunawar** [comment]
@magedhelmy1 Can you send the pull request again? I think, its is reverted when I changed the commit description.

**Comment by RizwanMunawar** [comment]
@lordfarquad3211 @magedhelmy1 The save-txt module is added for segmentation. You can use the mentioned command below to get coordinates of segmented area.
`python3 segment/predict.py --weights yolov7-seg.pt --source "videopath.mp4" --save-txt`

I am closing this issue, because the module is completed. Feel free to open new issue if you will face any problems.
