### ISSUE TITLE
How can I obtain only segmentation mask without bounding box?

### ISSUE THREAD

**Issue by ytl0623** [RizwanMunawar/yolov7-segmentation#63]
Hi, excuse me.

The result with code is a image with segmentation mask and bounding box (like object detection).
But I only want to store the mask region.
So, how can I obtain only segmentation mask without bounding box?

Thanks!!!

**Comment by ytl0623** [comment]
I found the way. Thanks.

**Comment by hdm30** [comment]
could you please share how you did it?

**Comment by amelieLePanda** [comment]
@ytl0623 could you please share how you did this?
